version: '3.8'
services:
  backend:
    image: light-backend:latest
    ports:
      - "3001:3001"
    environment:
      - LIGHT_DB_PATH=/app/data/light.db
      - LIGHT_STATIC_PATH=/app/light/public
      - LIGHT_ASSETS_PATH=/app/light/public/uploads
      - LIGHT_UPLOAD_DIR=/app/light/public/uploads
      - LIGHT_UPLOAD_BASE_URL=http://localhost:3001
    volumes:
      - ./service-java/light/public:/app/light/public
      - ./service-java/data:/app/data
  web:
    image: light-web:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
      - /etc/admin-web-nginx-conf:/etc/nginx/conf.d:ro
  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
  cms:
    image: light-cms:latest
    ports:
      - "17070:80"
      - "17072:443"
    depends_on:
      - backend
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
      - /etc/admin-cms-nginx-conf:/etc/nginx/conf.d:ro
