 .dockerignore                                      |   32 [32m+[m[31m-[m
 .gitignore                                         |   32 [32m+[m[31m-[m
 .vscode/settings.json                              |    4 [32m+[m[31m-[m
 DOCKER_DEPLOYMENT.md                               |  118 [32m++[m[31m-[m
 LOGIN_SYSTEM.md                                    |  421 [32m++++[m[31m----[m
 docker-compose.yml                                 |   78 [32m+[m[31m-[m
 light-cms/.dockerignore                            |   28 [32m+[m[31m-[m
 light-cms/.umirc.ts                                |  219 [32m++[m[31m--[m
 light-cms/API.md                                   |  408 [32m++++[m[31m----[m
 light-cms/API_DOCUMENTATION.md                     |  848 [32m++++++++[m[31m--------[m
 light-cms/Dockerfile                               |   30 [32m+[m[31m-[m
 light-cms/nginx.conf                               |  100 [32m+[m[31m-[m
 light-cms/src/app.ts                               |  246 [32m++[m[31m---[m
 light-cms/src/components/ImageUpload/index.js      |  338 [32m+++[m[31m----[m
 light-cms/src/components/LanguageTab/index.js      |  300 [32m+++[m[31m---[m
 light-cms/src/pages/404.tsx                        |   40 [32m+[m[31m-[m
 light-cms/src/pages/Category/edit.js               |  238 [32m++[m[31m---[m
 light-cms/src/pages/Featured/edit.js               |  314 [32m+++[m[31m---[m
 light-cms/src/pages/Language/edit.js               |  192 [32m++[m[31m--[m
 light-cms/src/pages/Login/index.tsx                |  195 [32m++[m[31m--[m
 light-cms/src/pages/Product/edit.js                |  582 [32m+++++[m[31m------[m
 light-cms/src/pages/Product/index.js               |  320 [32m+++[m[31m---[m
 light-cms/src/pages/Settings/index.js              |  300 [32m+++[m[31m---[m
 light-cms/src/pages/Welcome/index.less             |  122 [32m+[m[31m--[m
 light-cms/src/pages/Welcome/index.tsx              |   62 [32m+[m[31m-[m
 light-cms/src/services/index.js                    |   10 [32m+[m
 light-cms/src/utils/notifyFormValidateError.js     |   60 [32m+[m[31m-[m
 light-vite/.dockerignore                           |   28 [32m+[m[31m-[m
 light-vite/Dockerfile                              |   30 [32m+[m[31m-[m
 light-vite/index.html                              |   30 [32m+[m[31m-[m
 light-vite/nginx.conf                              |   52 [32m+[m[31m-[m
 light-vite/src/components/Logo.jsx                 |   48 [32m+[m[31m-[m
 light-vite/src/components/layout/Layout.jsx        |   50 [32m+[m[31m-[m
 light-vite/src/components/layout/Navbar.jsx        |  312 [32m+++[m[31m---[m
 light-vite/src/hooks/useHomeData.js                |   84 [32m+[m[31m-[m
 light-vite/src/hooks/useProductCategories.js       |   64 [32m+[m[31m-[m
 light-vite/src/hooks/useProductDetail.js           |  242 [32m++[m[31m---[m
 light-vite/src/i18n/locales/ar.json                |  246 [32m++[m[31m---[m
 light-vite/src/i18n/locales/en.json                |  244 [32m++[m[31m---[m
 light-vite/src/i18n/locales/zh.json                |  244 [32m++[m[31m---[m
 light-vite/src/pages/Home/HomeAbout.jsx            |   60 [32m+[m[31m-[m
 light-vite/src/pages/Home/HomeGallery.jsx          |  104 [32m+[m[31m-[m
 light-vite/src/pages/Home/HomeMarquee.jsx          |   64 [32m+[m[31m-[m
 light-vite/src/pages/NotFound/index.jsx            |   56 [32m+[m[31m-[m
 light-vite/src/pages/ProductDetail/DetailSpecs.jsx |  104 [32m+[m[31m-[m
 light-vite/src/pages/ProductDetail/index.jsx       |  108 [32m+[m[31m-[m
 light-vite/src/pages/Products/CategoryBlock.jsx    |  112 [32m+[m[31m--[m
 light-vite/src/router/index.jsx                    |   48 [32m+[m[31m-[m
 .../src/styles/components/floating-contact.css     |  100 [32m+[m[31m-[m
 light-vite/src/styles/index.css                    |   28 [32m+[m[31m-[m
 light-vite/src/styles/pages/home.css               | 1048 [32m++++++++++[m[31m----------[m
 light-vite/src/styles