server:
  port: 3001

spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${LIGHT_DB_PATH:../../services/data/light.db}

light:
  static-path: ${LIGHT_STATIC_PATH:../../light/public}
  assets-path: ${LIGHT_ASSETS_PATH:../../light/public/uploads}
  upload-dir: ${LIGHT_UPLOAD_DIR:../../light/public/uploads}
