export const getColumns = () => [
  {
    width: 70,
    title: '序号',
    align: 'center',
    fixed: 'left',
    render: (text, value, index) => index + 1,
  },
  {
    title: '姓名',
    dataIndex: 'name',
    align: 'center',
    width: 120,
    ellipsis: true,
    sorter: true,
  },
  {
    title: '邮箱',
    dataIndex: 'email',
    align: 'center',
    width: 200,
    ellipsis: true,
    sorter: true,
  },
  {
    title: '国家',
    dataIndex: 'country',
    align: 'center',
    width: 100,
    ellipsis: true,
    render: (v) => v || '—',
  },
  {
    title: '电话',
    dataIndex: 'tel',
    align: 'center',
    width: 130,
    ellipsis: true,
    render: (v) => v || '—',
  },
  {
    title: '留言摘要',
    dataIndex: 'message',
    align: 'left',
    ellipsis: true,
    width: 240,
  },
  {
    title: '提交时间',
    dataIndex: 'created_at',
    align: 'center',
    width: 170,
    sorter: true,
  },
];
